In [1]:
import pandas as pd

df = pd.read_csv("trial_data.csv")
df.shape

(2000, 10)

In [2]:
!pip install lifelines

Defaulting to user installation because normal site-packages is not writeable
Collecting lifelines
  Downloading lifelines-0.30.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.14.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from lifelines) (2.4.2)
Collecting scipy>=1.7.0 (from lifelines)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting pandas<3.0,>=2.1 (from lifelines)
  Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting matplotlib>=3.0 (from lifelines)
  Using cached matplotlib-3.10.8-cp311-cp311-win_amd64.whl.metadata (52 kB)
Collecting autograd>=1.5 (from lifelines)
  Downloading autograd-1.8.0-py3-none-any.whl.metadata (7.5 kB)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from pandas<3.0,>=2.1->lifelines) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas<3.0,>=2.1->lifelines)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from pandas<3.0,>=2.1->lifelines) (2025.3)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Collecting narwhals>=1.17 (from formulaic>=0.2.2->lifelines)
  Downloading narwhals-2.17.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Collecting wrapt>=1.0 (from formulaic>=0.2.2->lifelines)
  Using cached wrapt-2.1.1-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.0->lifelines)
  Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.0->lifelines)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.0->lifelines)
  Using cached fonttools-4.61.1-cp311-cp311-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.0->lifelines)
  Using cached kiwisolver-1.4.9-cp311-cp311-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from matplotlib>=3.0->lifelines) (26.0)
Collecting pillow>=8 (from matplotlib>=3.0->lifelines)
  Downloading pillow-12.1.1-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib>=3.0->lifelines)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=2.1->lifelines) (1.17.0)
Downloading lifelines-0.30.1-py3-none-any.whl (350 kB)
Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
Downloading autograd-1.8.0-py3-none-any.whl (51 kB)
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Using cached matplotlib-3.10.8-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp311-cp311-win_amd64.whl (225 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp311-cp311-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp311-cp311-win_amd64.whl (73 kB)
Downloading narwhals-2.17.0-py3-none-any.whl (444 kB)
Downloading pillow-12.1.1-cp311-cp311-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.0 MB 4.2 MB/s eta 0:00:02
   -------- ------------------------------- 1.6/7.0 MB 3.8 MB/s eta 0:00:02
   ------------- -------------------------- 2.4/7.0 MB 3.8 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.0 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 3.9/7.0 MB 3.9 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.0 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.0 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.0 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 3.9 MB/s  0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
    --------------------------------------- 0.8/36.6 MB 3.7 MB/s eta 0:00:10
   - -------------------------------------- 1.6/36.6 MB 4.0 MB/s eta 0:00:09
   -- ------------------------------------- 2.4/36.6 MB 3.8 MB/s eta 0:00:09
   --- ------------------------------------ 3.1/36.6 MB 3.8 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/36.6 MB 3.9 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/36.6 MB 3.9 MB/s eta 0:00:09
   ------ --------------------------------- 5.5/36.6 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 6.6/36.6 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 7.3/36.6 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 8.1/36.6 MB 3.9 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/36.6 MB 3.9 MB/s eta 0:00:08
   ---------- ----------------------------- 9.7/36.6 MB 3.9 MB/s eta 0:00:07
   ----------- ---------------------------- 10.5/36.6 MB 3.9 MB/s eta 0:00:07
   ------------ --------------------------- 11.3/36.6 MB 3.9 MB/s eta 0:00:07
   ------------- -------------------------- 12.1/36.6 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 12.8/36.6 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 13.6/36.6 MB 3.9 MB/s eta 0:00:06
   --------------- ------------------------ 14.4/36.6 MB 3.9 MB/s eta 0:00:06
   ---------------- ----------------------- 15.2/36.6 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 16.0/36.6 MB 3.9 MB/s eta 0:00:06
   ------------------ --------------------- 16.8/36.6 MB 3.9 MB/s eta 0:00:06
   ------------------- -------------------- 17.6/36.6 MB 3.9 MB/s eta 0:00:05
   -------------------- ------------------- 18.4/36.6 MB 3.9 MB/s eta 0:00:05
   -------------------- ------------------- 19.1/36.6 MB 3.9 MB/s eta 0:00:05
   --------------------- ------------------ 19.9/36.6 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 20.7/36.6 MB 3.9 MB/s eta 0:00:05
   ----------------------- ---------------- 21.8/36.6 MB 3.9 MB/s eta 0:00:04
   ------------------------ --------------- 22.5/36.6 MB 3.9 MB/s eta 0:00:04
   ------------------------- -------------- 23.3/36.6 MB 3.9 MB/s eta 0:00:04
   -------------------------- ------------- 24.1/36.6 MB 3.9 MB/s eta 0:00:04
   --------------------------- ------------ 24.9/36.6 MB 3.9 MB/s eta 0:00:04
   ---------------------------- ----------- 25.7/36.6 MB 3.9 MB/s eta 0:00:03
   ---------------------------- ----------- 26.5/36.6 MB 3.9 MB/s eta 0:00:03
   ------------------------------ --------- 27.5/36.6 MB 3.9 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/36.6 MB 3.9 MB/s eta 0:00:03
   ------------------------------- -------- 29.1/36.6 MB 3.9 MB/s eta 0:00:02
   -------------------------------- ------- 29.9/36.6 MB 3.9 MB/s eta 0:00:02
   --------------------------------- ------ 30.7/36.6 MB 3.9 MB/s eta 0:00:02
   ---------------------------------- ----- 31.5/36.6 MB 3.9 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.6 MB 3.9 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 3.9 MB/s  0:00:09
Using cached wrapt-2.1.1-cp311-cp311-win_amd64.whl (60 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (pyproject.toml): started
  Building wheel for autograd-gamma (pyproject.toml): finished with status 'done'
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4138 sha256=9ebc07b3b1d3a1b6ac53d8bd6afc54001a657976744ed4ddee2d182aef4aa339
  Stored in directory: c:\users\sushant\appdata\local\pip\cache\wheels\8b\67\f4\2caaae2146198dcb824f31a303833b07b14a5ec863fb3acd7b
Successfully built autograd-gamma
Installing collected packages: pytz, wrapt, scipy, pyparsing, pillow, narwhals, kiwisolver, interface-meta, fonttools, cycler, contourpy, autograd, pandas, matplotlib, autograd-gamma, formulaic, lifelines

   ----------------------------------------  0/17 [pytz]
   ----------------------------------------  0/17 [pytz]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ---- -----------------------------------  2/17 [scipy]
   ------- --------------------------------  3/17 [pyparsing]
   ------- --------------------------------  3/17 [pyparsing]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   --------- ------------------------------  4/17 [pillow]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ----------- ----------------------------  5/17 [narwhals]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ------------------ ---------------------  8/17 [fonttools]
   ----------------------- ---------------- 10/17 [contourpy]
   ------------------------- -------------- 11/17 [autograd]
   ------------------------- -------------- 11/17 [autograd]
  Attempting uninstall: pandas
   ------------------------- -------------- 11/17 [autograd]
    Found existing installation: pandas 3.0.0
   ------------------------- -------------- 11/17 [autograd]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
    Uninstalling pandas-3.0.0:
   ---------------------------- ----------- 12/17 [pandas]
      Successfully uninstalled pandas-3.0.0
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]
   ---------------------------- ----------- 12/17 [pandas]

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\Sushant\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages\~andas'.
  You can safely remove it manually.

In [3]:
from lifelines import CoxPHFitter

cph = CoxPHFitter()
cph.fit(df, duration_col="time", event_col="event")

cph.print_summary()

<lifelines.CoxPHFitter: fitted with 2000 total observations, 1373 right-censored observations>
             duration col = 'time'
                event col = 'event'
      baseline estimation = breslow
   number of observations = 2000
number of events observed = 627
   partial log-likelihood = -4603.19
         time fit was run = 2026-02-27 08:27:47 UTC

---
             coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
treatment   -0.29      0.75      0.08           -0.45           -0.13                0.64                0.87
age          0.00      1.00      0.00           -0.00            0.01                1.00                1.01
hr_status    0.30      1.35      0.23           -0.15            0.75                0.86                2.13
her2_status  0.23      1.25      0.11            0.00            0.45                1.00                1.57
tnbc         0.94      2.57      0.25            0.45            1.44                1.57                4.20
tumor_size   0.23      1.25      0.06            0.12            0.34                1.12                1.40
nodes        0.28      1.32      0.05            0.17            0.38                1.19                1.46
grade        0.13      1.14      0.06            0.01            0.25                1.01                1.28

             cmp to     z      p  -log2(p)
covariate
treatment      0.00 -3.63 <0.005     11.79
age            0.00  1.12   0.26      1.94
hr_status      0.00  1.30   0.20      2.36
her2_status    0.00  1.96   0.05      4.32
tnbc           0.00  3.77 <0.005     12.60
tumor_size     0.00  3.99 <0.005     13.86
nodes          0.00  5.21 <0.005     22.36
grade          0.00  2.13   0.03      4.92
---
Concordance = 0.61
Partial AIC = 9222.37
log-likelihood ratio test = 104.44 on 8 df
-log2(p) of ll-ratio test = 60.72

In [4]:
cph.concordance_index_

np.float64(0.6134466977321444)

In [5]:
!pip install scikit-survival

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-survival
  Downloading scikit_survival-0.27.0-cp311-cp311-win_amd64.whl.metadata (7.1 kB)
Collecting ecos (from scikit-survival)
  Downloading ecos-2.0.14-cp311-cp311-win_amd64.whl.metadata (8.2 kB)
Collecting joblib (from scikit-survival)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting numexpr (from scikit-survival)
  Downloading numexpr-2.14.1-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=2.0.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from scikit-survival) (2.4.2)
Collecting osqp>=1.0.2 (from scikit-survival)
  Downloading osqp-1.1.1-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Requirement already satisfied: pandas>=2.2.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from scikit-survival) (2.3.3)
Requirement already satisfied: scipy>=1.13.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from scikit-survival) (1.17.1)
Collecting scikit-learn<1.9,>=1.8.0 (from scikit-survival)
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn<1.9,>=1.8.0->scikit-survival)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: jinja2 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from osqp>=1.0.2->scikit-survival) (3.1.6)
Requirement already satisfied: setuptools in C:\Program Files\Python311\Lib\site-packages (from osqp>=1.0.2->scikit-survival) (65.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from pandas>=2.2.0->scikit-survival) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from pandas>=2.2.0->scikit-survival) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from pandas>=2.2.0->scikit-survival) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->scikit-survival) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Sushant\AppData\Roaming\Python\Python311\site-packages (from jinja2->osqp>=1.0.2->scikit-survival) (3.0.3)
Downloading scikit_survival-0.27.0-cp311-cp311-win_amd64.whl (801 kB)
   ---------------------------------------- 0.0/802.0 kB ? eta -:--:--
   ---------------------------------------- 802.0/802.0 kB 6.9 MB/s  0:00:00
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.1 MB 3.8 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.1 MB 3.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.1 MB 3.8 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.1 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.1 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 3.9 MB/s  0:00:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading osqp-1.1.1-cp311-cp311-win_amd64.whl (310 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading ecos-2.0.14-cp311-cp311-win_amd64.whl (72 kB)
Downloading numexpr-2.14.1-cp311-cp311-win_amd64.whl (160 kB)
Installing collected packages: threadpoolctl, numexpr, joblib, scikit-learn, osqp, ecos, scikit-survival

   ----------- ---------------------------- 2/7 [joblib]
   ----------- ---------------------------- 2/7 [joblib]
   ----------- ---------------------------- 2/7 [joblib]
   ----------- ---------------------------- 2/7 [joblib]
   ----------- ---------------------------- 2/7 [joblib]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ----------------- ---------------------- 3/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [osqp]
   ---------------------------- ----------- 5/7 [ecos]
   ---------------------------------- ----- 6/7 [scikit-survival]
   ---------------------------------- ----- 6/7 [scikit-survival]
   ---------------------------------------- 7/7 [scikit-survival]

Successfully installed ecos-2.0.14 joblib-1.5.3 numexpr-2.14.1 osqp-1.1.1 scikit-learn-1.8.0 scikit-survival-0.27.0 threadpoolctl-3.6.0

In [6]:
import numpy as np
from sksurv.util import Surv

# Define outcome
y = Surv.from_dataframe("event", "time", df)

# Define features (drop time & event)
X = df.drop(columns=["time", "event"])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [8]:
from sksurv.ensemble import RandomSurvivalForest

rsf = RandomSurvivalForest(
    n_estimators=200,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features="sqrt",
    n_jobs=-1,
    random_state=42
)

rsf.fit(X_train, y_train)

RandomSurvivalForest(min_samples_leaf=5, min_samples_split=10, n_estimators=200,
                     n_jobs=-1, random_state=42)

In [9]:
from sksurv.metrics import concordance_index_censored

# Predict risk scores
risk_scores = rsf.predict(X_test)

c_index = concordance_index_censored(
    y_test["event"],
    y_test["time"],
    risk_scores
)

c_index

(np.float64(0.5846149633037573),
 np.int64(53366),
 np.int64(37917),
 np.int64(7),
 np.int64(0))